/**
 * Builds the icon sprite in src/index.html from Phosphor Icons (MIT, @phosphor-icons/core).
 *
 * Mark an icon in the HTML as
 *     <svg class="ico" data-icon="gear-six" data-weight="duo" data-alt="fill"></svg>
 * and run `npm run icons`. The script fills each such <svg> with <use> references and writes the
 * symbols it needs between the `icons:start` / `icons:end` comments, so only the icons the app
 * uses are bundled and nothing is loaded at runtime. Icons built from JS take the same markup.
 *
 * Weights: bold, fill, regular, duotone, and `duo` (the bold outline over duotone's tinted
 * fill, which Phosphor does not ship). `data-weight` defaults to bold. `data-alt` adds a second
 * weight that CSS shows for active or hovered buttons (`.ico-alt`).
 *
 * `JS_ICONS` lists icons that only appear in markup built by renderer scripts.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const HTML = path.join(ROOT, 'src', 'index.html');
const ASSETS = path.join(ROOT, 'node_modules', '@phosphor-icons', 'core', 'assets');
const JS_ICONS = [['folder-open', 'duo'], ['plus', 'bold']];

const ICON_TAG = /<svg class="ico([^"]*)" data-icon="([a-z0-9-]+)"([^>]*)>[\s\S]*?<\/svg>/g;
const attr = (attrs, name) => (attrs.match(new RegExp(`${name}="([a-z]+)"`)) || [])[1];

function readWeight(name, weight) {
    const file = weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`;
    const svg = fs.readFileSync(path.join(ASSETS, weight, file), 'utf8');
    return svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
}

function symbolBody(name, weight) {
    if (weight !== 'duo') return readWeight(name, weight);
    const tint = readWeight(name, 'duotone').match(/<[^>]+opacity="0\.2"[^>]*\/>/g) || [];
    return tint.join('') + readWeight(name, 'bold');
}

const symbolId = (name, weight) => `i-${name}${weight === 'bold' ? '' : '-' + weight}`;

let html = fs.readFileSync(HTML, 'utf8');
const used = new Map();
const need = (name, weight) => used.set(symbolId(name, weight), [name, weight]);
JS_ICONS.forEach(([name, weight]) => need(name, weight || 'bold'));

html = html.replace(ICON_TAG, (_, cls, name, attrs) => {
    const weight = attr(attrs, 'data-weight') || 'bold';
    const alt = attr(attrs, 'data-alt');
    need(name, weight);
    let uses = `<use href="#${symbolId(name, weight)}"/>`;
    if (alt) {
        need(name, alt);
        uses += `<use class="ico-alt" href="#${symbolId(name, alt)}"/>`;
    }
    return `<svg class="ico${cls}" data-icon="${name}"${attrs}>${uses}</svg>`;
});

const symbols = [...used].sort(([a], [b]) => a.localeCompare(b))
    .map(([id, [name, weight]]) => `<symbol id="${id}" viewBox="0 0 256 256">${symbolBody(name, weight)}</symbol>`);
const sprite = '<!-- icons:start (generated by scripts/build-icons.js from Phosphor Icons, MIT) -->\n' +
    `    <svg id="icon-sprite" aria-hidden="true" style="display:none">${symbols.join('')}</svg>\n` +
    '    <!-- icons:end -->';

if (!/<!-- icons:start[\s\S]*?<!-- icons:end -->/.test(html)) {
    throw new Error('src/index.html has no <!-- icons:start --> ... <!-- icons:end --> block');
}
html = html.replace(/<!-- icons:start[\s\S]*?<!-- icons:end -->/, sprite);
fs.writeFileSync(HTML, html);
console.log(`icons: ${used.size} symbols, ${(Buffer.byteLength(sprite) / 1024).toFixed(1)} KB`);
